# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
before_script:
  - Rscript -e 'vaultr::vault_test_server_install()'
  - R CMD INSTALL .
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
env:
  global:
    - VAULTR_TEST_SERVER_INSTALL=true
    - VAULTR_TEST_SERVER_PORT=18200
    - VAULTR_TEST_SERVER_BIN_PATH=$PWD/.vault
