on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: docker-image

jobs:
  docker-image:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      VAULTR_TEST_SERVER_INSTALL: true
      VAULTR_TEST_SERVER_PORT: 18200

    steps:
      - uses: actions/checkout@v2

      - name: build
        run:  ./docker/build

      - name: push
        run: ./docker/push
